# Use the official Nginx image as the base image
FROM nginx:latest

# Set the working directory inside the container
WORKDIR /usr/share/nginx/html

# Copy the contents of your frontend app to the container
COPY . .

# Expose port 80 to the outside world
EXPOSE 80